apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-tjrh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-tjrh
    app.kubernetes.io/part-of: tkrw-pr714-0075-0065-app
  name: devfile-sample-tjrh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-tjrh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-tjrh
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0065-tenant/tkrw-pr714-0075-0065-app/devfile-sample-tjrh@sha256:0f77c43262dfa410f652e7a8b7c23bcba8afa3d5383c63c9e609debd1d263cc4
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
